import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#121212",
    padding: 20,
    alignItems: "center",
    justifyContent: "flex-start",
  },
  scrollContainer: {
    flexGrow: 1,
    height: 1200,
  },
  dadosText: {
    color: "#FFF",
    fontFamily: "JetBrainsMono",
    fontSize: 18,
    paddingBottom: 8,
    textAlign: "center",
  },
  containerUsuario: {
    backgroundColor: "#1E1E1E",
    width: "100%",
    padding: 20,
    borderRadius: 15,
    borderWidth: 2,
    borderColor: "#FFF",
    marginBottom: 30,
  },
  input: {
    backgroundColor: "#2A2A2A",
    color: "#FFF",
    fontFamily: "JetBrainsMono",
    padding: 14,
    borderRadius: 12,
    marginBottom: 15,
    borderWidth: 1.5,
    borderColor: "#FFF",
    width: "100%",
  },
  inputbd: {
    backgroundColor: "#2A2A2A",
    color: "#FFF",
    fontFamily: "JetBrainsMono",
    fontSize: 12,
    padding: 10,
    borderRadius: 12,
    marginBottom: 15,
    borderWidth: 1.5,
    borderColor: "#FFF",
    width: "100%",
    height: 300,
    textAlignVertical: 'top',
  },
  button: {
    backgroundColor: '#92FFFF',
    paddingVertical: 12,
    alignItems: 'center',
    width: '50%',
    borderRadius: 20,
    alignSelf: 'center',
    marginTop: 15,
  },
  botaoTexto: {
    color: "#121212",
    fontFamily: "JetBrainsMono",
    fontSize: 16,
    fontWeight: "bold",
  },
  containerVisualizar: {
    backgroundColor: "#1E1E1E",
    width: "100%",
    padding: 15,
    borderRadius: 15,
    borderWidth: 1,
    borderColor: "#FFF",
  },
  agentCard: {
    backgroundColor: "#2A2A2A",
    padding: 15,
    borderRadius: 12,
    marginBottom: 15,
    borderWidth: 1,
    borderColor: "#444",
  },
  agentName: {
    fontSize: 18,
    color: "#92FFFF",
    fontFamily: "JetBrainsMono",
    fontWeight: "bold",
  },
  agentDescription: {
    fontSize: 14,
    color: "#EEE",
    marginTop: 5,
    fontFamily: "JetBrainsMono",
  },
  agentActions: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginTop: 10,
  },
  editButton: {
    backgroundColor: "#4756fc",
    paddingVertical: 8,
    paddingHorizontal: 16,
    borderRadius: 8,
  },
  deleteButton: {
    backgroundColor: "#bf3939",
    paddingVertical: 8,
    paddingHorizontal: 16,
    borderRadius: 8,
  },
  buttonText: {
    color: "#FFF",
    fontFamily: "JetBrainsMono",
    fontSize: 12,
    fontWeight: "bold",
  },
  modalContainer: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.7)',
    justifyContent: 'center',
    alignItems: 'center',
    padding: 20,
  },
  modalContent: {
    backgroundColor: "#1E1E1E",
    width: "100%",
    borderRadius: 15,
    padding: 20,
    borderWidth: 2,
    borderColor: "#92FFFF",
  },
  modalTitle: {
    color: "#92FFFF",
    fontSize: 20,
    fontWeight: "bold",
    fontFamily: "JetBrainsMono",
    marginBottom: 15,
  },
  containerbotoes: {
    flexDirection: "row",
    justifyContent: "space-around",
    marginTop: 20,
  },
  cancelButton: {
    backgroundColor: "red",
    paddingVertical: 12,
    alignItems: "center",
    width: "40%",
    borderRadius: 20,
    alignSelf: "center",
    marginTop: 10,
  },
});