import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#000",
    padding: 10,
    gap: 10,
  },
  titulo: {
    color: "#fff",
    fontSize: 24,
  },
  subtitulo: {
    color: "#fff",
    fontSize: 15,
    padding: 10,
  },
  subtitulo2: {
    color: "#fff",
    fontSize: 12,
    padding: 10,
  },
  subtitulo3: {
    color: "#fff",
    fontSize: 9,
    padding: 6,
  },
  userText: {
    color: "#26a3ff",
  },
  pesquisar: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#111",
    padding: 10,
    borderRadius: 8,
    marginVertical: 10,
    borderWidth: 1,
    borderColor: "#26a3ff",
  },
  input: {
    flex: 1,
    color: "#fff",
    padding: 5,
    fontSize: 16,
  },
  chats: {
    height: 190, 
    backgroundColor: "#121212",
    borderColor: "#FC82FF",
    borderRadius: 8,
    borderWidth: 1,
    padding: 10,
    justifyContent: "center",
  },
  containerChats: {
    flexDirection: "row",
    justifyContent: "flex-start",
    alignItems: "center",
    gap: 8,
    paddingHorizontal: 5,
  },
  agentesChats: {
    height: 130,
    width: 110,
    borderRadius: 8,
    paddingTop: 15,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#333333",
  },
  imagemBots: {
    height: 95,
    width: 95,
    borderRadius: 10,
  },
  historico: {
    backgroundColor: "#121212",
    borderColor: "#9182FF",
    borderRadius: 8,
    borderWidth: 1,
    padding: 10,
    justifyContent: "center",
  },
  scrollContainer: {
    maxHeight: 250,
  },
  containerHistorico: {
    flexDirection: "column", 
    justifyContent: "center",
    alignItems: "center", 
    gap: 8, 
    paddingHorizontal: 5,
  },
  agentesHistorico: {
    height: 65,
    width: "95%",
    flexDirection: 'row',  
    borderRadius: 8,
    padding: 7,
    backgroundColor: "#333333",
    alignItems: "center",  
    gap: 10,
  },
  imagemBotsHistorico: {
    height: 40,
    width: 40,
    borderRadius: 10,
  },
  botInfo: {
    flexDirection: "column", 
    justifyContent: "center",
    width: 300,
  },
});
