import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#121212",
    padding: 10,
    alignItems: "center",
    justifyContent: "flex-start",
  },
  titulo: {
    color: "#92FFFF",
    fontSize: 32,
    fontWeight: "bold",
    paddingVertical: 20,
    fontFamily: "JetBrainsMono",
    textAlign: "center",
  },
  containerTitulo: {
    width: "100%",
    alignItems: "center",
  },
  dadosText: {
    color: "#FFF",
    fontFamily: "JetBrainsMono",
    fontSize: 16,
    paddingBottom: 5,
  },
  containerUsuario: {
    backgroundColor: "#1E1E1E", 
    height: "70%",
    width: "90%",
    padding: 15,
    borderRadius: 12,
    borderWidth: 2,
    borderColor: "#FFF",
    shadowColor: "#000",
    shadowOpacity: 0.3,
    shadowOffset: { width: 0, height: 4 },
    shadowRadius: 5,
    gap: 5,
    elevation: 5,
  },
  input: {
    backgroundColor: "#2A2A2A",
    color: "#FFF",
    fontFamily: "JetBrainsMono",
    padding: 12,
    borderRadius: 10,
    marginBottom: 10,
    borderWidth: 1.5,
    borderColor: "#FFF",
    width: "100%",
  },
  inputTipo: {
    backgroundColor: "#2A2A2A",
    color: "#FFF",
    fontFamily: "JetBrainsMono",
    paddingVertical: 10,
    borderRadius: 10,
    borderWidth: 1.5,
    borderColor: "#FFF",
    width: "100%",
    height: 50,
    justifyContent: "center",
  },
  button: {
    backgroundColor: '#92FFFF',
    padding: 10,
    alignItems: 'center',
    width: '30%',
    display: 'flex',
    borderRadius: 15,
    borderColor: 'white',
    marginHorizontal: 120,
    marginTop: 10,
    },
  botaoTexto: {
    color: "#121212",
    fontFamily: "JetBrainsMono",
    fontSize: 15,
    fontWeight: "bold",
  },
});
