import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#000",
    padding: 5,
    alignItems: "center",
    justifyContent: "flex-start",
    gap: 10,
  },
  titulo: {
    color: "#fff",
    fontSize: 25,
    paddingTop: "5%",
    paddingBottom: "5%",
    fontFamily: 'JetBrainsMono',
    textAlign: 'center', 
    justifyContent: 'space-between',
  },
  containerTitulo: {
    alignItems: "flex-start",
    width: "90%",
    flexDirection: "row",
  },
  userText: {
    color: "#92FFFF",
    fontFamily: 'JetBrainsMono',
    fontSize: 25,
  },
  dadosText: {
    color: "white",
    fontFamily: 'JetBrainsMono',
    fontSize: 20,
  },
  fotoUsuario: {
    alignItems: "center",
  },
  foto: {
    borderRadius: 100,
    display: 'flex',
    height: 100,
    width: 100,
  },
  containerDados: {
    alignItems: "flex-start",
    width: "90%",
  },
  containerConfiguracoes: {
    backgroundColor: "#111",
    width: "90%",
    height: "60%",
    padding: 8,
    display: "flex", 
    borderColor: "#92FFFF",
    borderWidth: 3,
    borderRadius: 8,
    gap: 7,
  },
  input: {
    backgroundColor: "#2A2A2A",  
    color: "#FFF",
    fontFamily: "JetBrainsMono",
    padding: 14,
    borderRadius: 12,
    marginBottom: 15,  
    borderWidth: 1.5,
    borderColor: "#FFF",
    width: "100%",
  },
  button: {
    backgroundColor: '#92FFFF',
    paddingVertical: 12,
    alignItems: 'center',
    width: '40%',  
    borderRadius: 20,  
    borderColor: 'white',  
    marginBottom: 5,  
  },
  botaoTexto: {
    color: "#121212", 
    fontFamily: "JetBrainsMono",
    fontSize: 14, 
    fontWeight: "bold",
  },
  inputTipo: {
    backgroundColor: "#2A2A2A",
    color: "#FFF",
    fontFamily: "JetBrainsMono",
    paddingVertical: 12, 
    borderRadius: 12,
    borderWidth: 1.5,
    borderColor: "#FFF",
    width: "100%",
    height: 55, 
    justifyContent: "center",
  },
  scrollContainer: {
    flexGrow: 1,
    height: 800,
  },
});
